export const topPayersData = [
  {
    id: 1,
    name: "Amit Verma",
    flat: "A-403",
    apartment: "Green View Apartment",
    avatar: "AV",
    totalPaid: 245000,
    payments: 7,
    lastPayment: "20 May 2025",
  },
  {
    id: 2,
    name: "Suresh Yadav",
    flat: "B-203",
    apartment: "Green View Apartment",
    avatar: "SY",
    totalPaid: 198600,
    payments: 6,
    lastPayment: "18 May 2025",
  },
  {
    id: 3,
    name: "Priya Sharma",
    flat: "C-302",
    apartment: "Green View Apartment",
    avatar: "PS",
    totalPaid: 175500,
    payments: 6,
    lastPayment: "15 May 2025",
  },
  {
    id: 4,
    name: "Rajesh Kumar",
    flat: "A-101",
    apartment: "Green View Apartment",
    avatar: "RK",
    totalPaid: 150000,
    payments: 5,
    lastPayment: "12 May 2025",
  },
  {
    id: 5,
    name: "Deepak Joshi",
    flat: "B-501",
    apartment: "Green View Apartment",
    avatar: "DJ",
    totalPaid: 125400,
    payments: 5,
    lastPayment: "10 May 2025",
  },
  {
    id: 6,
    name: "Neha Patil",
    flat: "D-104",
    apartment: "Green View Apartment",
    avatar: "NP",
    totalPaid: 110000,
    payments: 4,
    lastPayment: "09 May 2025",
  },
  {
    id: 7,
    name: "Manoj Singh",
    flat: "A-604",
    apartment: "Green View Apartment",
    avatar: "MS",
    totalPaid: 95000,
    payments: 4,
    lastPayment: "07 May 2025",
  },
  {
    id: 8,
    name: "Ramesh Gupta",
    flat: "C-502",
    apartment: "Green View Apartment",
    avatar: "RG",
    totalPaid: 88000,
    payments: 4,
    lastPayment: "05 May 2025",
  },
  {
    id: 9,
    name: "Anjali Mehta",
    flat: "D-201",
    apartment: "Green View Apartment",
    avatar: "AM",
    totalPaid: 75000,
    payments: 3,
    lastPayment: "04 May 2025",
  },
  {
    id: 10,
    name: "Vikram Malhotra",
    flat: "B-402",
    apartment: "Green View Apartment",
    avatar: "VM",
    totalPaid: 65000,
    payments: 3,
    lastPayment: "02 May 2025",
  },
];