import React from 'react'

export const membersData = [
  {
    id: 1,
    name: "Rahul Sharma",
    role: "Treasurer",
    type: "Committee Member",
    contact: "9876543210",
    email: "rahul.sharma@example.com",
    status: "Active",
    joinDate: "12 Mar 2023",
    image: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 2,
    name: "Priya Mehta",
    role: "Secretary",
    type: "Committee Member",
    contact: "9123456780",
    email: "priya.mehta@example.com",
    status: "Active",
    joinDate: "18 Apr 2023",
    image: "https://i.pravatar.cc/40?img=5",
  },
  {
    id: 3,
    name: "Amit Verma",
    role: "Member",
    type: "General Member",
    contact: "9988776655",
    email: "amit.verma@example.com",
    status: "Active",
    joinDate: "05 May 2023",
    image: "https://i.pravatar.cc/40?img=12",
  },
  {
    id: 4,
    name: "Neha Singh",
    role: "Member",
    type: "General Member",
    contact: "9871122334",
    email: "neha.singh@example.com",
    status: "Inactive",
    joinDate: "22 Jun 2023",
    image: "https://i.pravatar.cc/40?img=20",
  },
  {
    id: 5,
    name: "Suresh Patel",
    role: "Member",
    type: "General Member",
    contact: "9001122334",
    email: "suresh.patel@example.com",
    status: "Active",
    joinDate: "15 Jul 2023",
    image: "https://i.pravatar.cc/40?img=15",
  },
];

