export const requestData = [
  {
    id: "MR-2025-0012",
    title: "Water leakage in bathroom tap",
    description: "There is a continuous leakage in the bathroom tap...",
    category: "Plumbing",
    icon: "bi-droplet",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
    priority: "High",
    status: "Open",
    requestedDate: "24 May 2025",
    requestedTime: "09:15 AM",
    updatedDate: "24 May 2025",
    updatedTime: "09:15 AM",
    date: "2025-05-24",
  },
  {
    id: "MR-2025-0011",
    title: "Lift not working properly",
    description: "Lift gets stuck between floors.",
    category: "Electrical",
    icon: "bi-building",
    iconBg: "bg-indigo-50",
    iconColor: "text-indigo-600",
    priority: "Medium",
    status: "In Progress",
    requestedDate: "23 May 2025",
    requestedTime: "04:20 PM",
    updatedDate: "24 May 2025",
    updatedTime: "10:30 AM",
    date: "2025-05-25",
  },
  {
    id: "MR-2025-0010",
    title: "Lights not working in corridor",
    description: "Corridor lights are not working since yesterday.",
    icon: "bi-lightbulb",
    category: "Electrical",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
    priority: "Low",
    status: "Resolved",
    requestedDate: "20 May 2025",
    requestedTime: "08:45 AM",
    updatedDate: "21 May 2025",
    updatedTime: "03:10 PM",
    date: "2025-05-26",
  },
  {
    id: "MR-2025-0009",
    title: "Garbage not collected",
    description: "Garbage not collected since 2 days.",
    category: "Housekeeping",
    icon: "bi-trash3",
    iconBg: "bg-gray-100",
    iconColor: "text-gray-700",
    priority: "Medium",
    status: "Resolved",
    requestedDate: "18 May 2025",
    requestedTime: "11:20 AM",
    updatedDate: "19 May 2025",
    updatedTime: "09:40 AM",
    date: "2025-05-27",
  },
  {
    id: "MR-2025-0008",
    title: "Parking space issue",
    description: "Two wheeler parking is not available.",
    category: "Parking",
    icon: "bi-p-circle",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
    priority: "Low",
    status: "Closed",
    requestedDate: "16 May 2025",
    requestedTime: "07:50 PM",
    updatedDate: "17 May 2025",
    updatedTime: "12:15 PM",
    date: "2025-05-28",
  },
  {
    id: "MR-2025-0007",
    title: "Water filter not working",
    description: "RO water filter is not working properly.",
    category: "Plumbing",
    icon: "bi-droplet",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
    priority: "Medium",
    status: "In Progress",
    requestedDate: "15 May 2025",
    requestedTime: "09:10 AM",
    updatedDate: "23 May 2025",
    updatedTime: "05:05 PM",
    date: "2025-05-29",
  },
  {
    id: "MR-2025-0006",
    title: "Door lock repair",
    description: "Main door lock is loose and not closing.",
    category: "Carpentry",
    icon: "bi-tools",
    iconBg: "bg-red-50",
    iconColor: "text-red-500",
    priority: "Low",
    status: "Open",
    requestedDate: "14 May 2025",
    requestedTime: "06:30 PM",
    updatedDate: "14 May 2025",
    updatedTime: "06:30 PM",
    date: "2025-05-30",
  },
];