import { createContext, useContext, useState } from "react";

const ComplaintContext = createContext();

export const ComplaintProvider = ({ children }) => {

  const [complaints, setComplaints] = useState([
  {
    id: "CMP-2025-155",
    title: "Water leakage in bathroom",
    description: "Water is leaking continuously from the bathroom tap.",
    category: "Plumbing",
    categoryIcon: "bi-droplet-fill",
    raisedBy: "Supriya Sonawale",
    flatNo: "A-101",
    priority: "High",
    status: "Open",
    raisedOn: "21 Jun 2026",
    raisedTime: "09:15 AM",
    updatedOn: "21 Jun 2026",
    updatedTime: "09:15 AM",
  },
  {
    id: "CMP-2025-156",
    title: "Light not working",
    description: "Living room light stopped working.",
    category: "Electricity",
    categoryIcon: "bi-lightning-charge-fill",
    raisedBy: "Rahul Patil",
    flatNo: "B-203",
    priority: "Medium",
    status: "In Progress",
    raisedOn: "20 Jun 2026",
    raisedTime: "11:30 AM",
    updatedOn: "21 Jun 2026",
    updatedTime: "10:00 AM",
  },
  {
    id: "CMP-2025-157",
    title: "Low water pressure",
    description: "Very low water pressure in kitchen.",
    category: "Water",
    categoryIcon: "bi-water",
    raisedBy: "Anita Desai",
    flatNo: "C-012",
    priority: "Low",
    status: "Resolved",
    raisedOn: "19 Jun 2026",
    raisedTime: "08:45 AM",
    updatedOn: "20 Jun 2026",
    updatedTime: "04:20 PM",
  },
  {
    id: "CMP-2025-158",
    title: "Garbage not collected",
    description: "Garbage has not been collected for two days.",
    category: "Cleaning",
    categoryIcon: "bi-trash3-fill",
    raisedBy: "Sunita Sonawale",
    flatNo: "C-013",
    priority: "High",
    status: "Overdue",
    raisedOn: "20 Jun 2026",
    raisedTime: "07:30 AM",
    updatedOn: "22 Jun 2026",
    updatedTime: "09:40 AM",
  },
  {
    id: "CMP-2025-159",
    title: "Kitchen sink blockage",
    description: "Kitchen sink water is blocked.",
    category: "Plumbing",
    categoryIcon: "bi-droplet-fill",
    raisedBy: "Ramesh Jadhav",
    flatNo: "A-201",
    priority: "High",
    status: "Open",
    raisedOn: "22 Jun 2026",
    raisedTime: "02:10 PM",
    updatedOn: "22 Jun 2026",
    updatedTime: "02:10 PM",
  },
  {
    id: "CMP-2025-160",
    title: "Main switch issue",
    description: "Main switch trips frequently.",
    category: "Electricity",
    categoryIcon: "bi-lightning-charge-fill",
    raisedBy: "Priya Desai",
    flatNo: "B-102",
    priority: "Medium",
    status: "In Progress",
    raisedOn: "21 Jun 2026",
    raisedTime: "01:40 PM",
    updatedOn: "22 Jun 2026",
    updatedTime: "08:30 AM",
  },
  {
    id: "CMP-2025-161",
    title: "Main gate lock issue",
    description: "Security gate lock is damaged.",
    category: "Security",
    categoryIcon: "bi-shield-lock-fill",
    raisedBy: "Vikram Mehta",
    flatNo: "D-104",
    priority: "High",
    status: "Open",
    raisedOn: "22 Jun 2026",
    raisedTime: "10:15 AM",
    updatedOn: "22 Jun 2026",
    updatedTime: "10:15 AM",
  },
  {
    id: "CMP-2025-162",
    title: "Tap leakage in kitchen",
    description: "Kitchen tap leaking continuously.",
    category: "Water",
    categoryIcon: "bi-water",
    raisedBy: "Neha Kulkarni",
    flatNo: "A-303",
    priority: "Low",
    status: "Resolved",
    raisedOn: "19 Jun 2026",
    raisedTime: "06:20 PM",
    updatedOn: "20 Jun 2026",
    updatedTime: "11:15 AM",
  },
  {
    id: "CMP-2025-163",
    title: "Lift area not cleaned",
    description: "Cleaning staff missed the lift lobby.",
    category: "Cleaning",
    categoryIcon: "bi-trash3-fill",
    raisedBy: "Amit Shah",
    flatNo: "B-110",
    priority: "Medium",
    status: "In Progress",
    raisedOn: "21 Jun 2026",
    raisedTime: "09:00 AM",
    updatedOn: "22 Jun 2026",
    updatedTime: "12:20 PM",
  },
  {
    id: "CMP-2025-164",
    title: "CCTV camera not working",
    description: "Parking CCTV camera is offline.",
    category: "Security",
    categoryIcon: "bi-camera-video-fill",
    raisedBy: "Kiran Joshi",
    flatNo: "D-202",
    priority: "High",
    status: "Open",
    raisedOn: "22 Jun 2026",
    raisedTime: "08:30 PM",
    updatedOn: "22 Jun 2026",
    updatedTime: "08:30 PM",
  },
]);
const [categories, setCategories] = useState([
  {
    id: 1,
    name: "Plumbing",
    description:
      "Water leakage, pipe leakage, tap issues, overflow, etc.",
    icon: "bi-droplet",
    status: "Active",
  },
  {
    id: 2,
    name: "Electricity",
    description:
      "Light not working, fan issues, switch problems, power failure, etc.",
    icon: "bi-lightning-charge",
    status: "Active",
  },
  {
    id: 3,
    name: "Water",
    description:
      "Water supply issues, low pressure, storage tank problems.",
    icon: "bi-water",
    status: "Active",
  },
  {
    id: 4,
    name: "Cleaning",
    description:
      "Garbage collection, housekeeping and hygiene issues.",
    icon: "bi-trash3",
    status: "Active",
  },
  {
    id: 5,
    name: "Security",
    description:
      "CCTV, gate access, visitor and security concerns.",
    icon: "bi-shield-lock",
    status: "Active",
  },
  {
  id: 6,
  name: "Lift Maintenance",
  description: "Lift breakdowns, repairs and maintenance related complaints.",
  icon: "bi-arrow-up-square-fill",
  status: "Active",
},
{
  id: 7,
  name: "Parking",
  description: "Parking allocation, unauthorized parking and vehicle issues.",
  icon: "bi-p-square-fill",
  status: "Active",
},
{
  id: 8,
  name: "Garden",
  description: "Garden upkeep, landscaping and plant maintenance issues.",
  icon: "bi-flower1",
  status: "Inactive",
},
{
  id: 9,
  name: "Club House",
  description: "Club house booking, facilities and maintenance complaints.",
  icon: "bi-building",
  status: "Active",
},
{
  id: 10,
  name: "Common Area",
  description: "Lobby, corridor, staircase and common space issues.",
  icon: "bi-grid-fill",
  status: "Active",
},
{
  id: 11,
  name: "Internet",
  description: "Broadband, Wi-Fi and connectivity related complaints.",
  icon: "bi-wifi",
  status: "Active",
},
{
  id: 12,
  name: "Generator",
  description: "Power backup and generator maintenance issues.",
  icon: "bi-cpu-fill",
  status: "Active",
},
{
  id: 13,
  name: "Fire Safety",
  description: "Fire extinguisher, alarm and safety equipment complaints.",
  icon: "bi-fire",
  status: "Active",
},
{
  id: 14,
  name: "Visitor Management",
  description: "Visitor entry, gate pass and security desk issues.",
  icon: "bi-person-badge-fill",
  status: "Active",
},
{
  id: 15,
  name: "Pet Issues",
  description: "Pet nuisance and pet policy related complaints.",
  icon: "bi-heart-fill",
  status: "Inactive",
},
{
  id: 16,
  name: "Noise Complaint",
  description: "Loud music, construction noise and disturbance issues.",
  icon: "bi-volume-up-fill",
  status: "Active",
},
{
  id: 17,
  name: "Street Light",
  description: "Street light not working or maintenance requests.",
  icon: "bi-lightbulb-fill",
  status: "Active",
},
{
  id: 18,
  name: "Pest Control",
  description: "Mosquitoes, insects and pest control complaints.",
  icon: "bi-bug-fill",
  status: "Active",
},
{
  id: 19,
  name: "Swimming Pool",
  description: "Pool cleanliness and maintenance issues.",
  icon: "bi-water",
  status: "Active",
},
{
  id: 20,
  name: "Others",
  description: "Miscellaneous complaints not covered in other categories.",
  icon: "bi-three-dots",
  status: "Active",
}
]);

  return (
    <ComplaintContext.Provider
     value={{
  complaints,
  setComplaints,
  categories,
  setCategories
}}
    >
      {children}
    </ComplaintContext.Provider>
  );
};

export const useComplaint = () => useContext(ComplaintContext);