import profile1 from "../../assets/maintenanceAssets/profile1.jpg";
import profile2 from "../../assets/maintenanceAssets/profile2.jpg";
import profile3 from "../../assets/maintenanceAssets/profile3.jpg";
import profile4 from "../../assets/maintenanceAssets/profile4.avif";
import profile5 from "../../assets/maintenanceAssets/profile5.jpg";

export const requests = [
  {
    id: "REQ-013",
    title: "Lighting wire spark",
    description: "Ceiling fan stopped working",
    category: "Electrical",
    resident: "Priya Mehta",
    image: profile2,
    flat: "B-203",
    priority: "Medium",
    status: "In Progress",
    assigned: "Suresh Electrician",
    date: "2025-06-18",
    time: "02:15 AM",
  },
  {
    id: "REQ-001",
    title: "Water Leakage",
    description: "Water leakage in bathroom pipeline",
    category: "Plumbing",
    resident: "Rahul Sharma",
    image: profile1,
    flat: "A-101",
    priority: "High",
    status: "Pending",
    assigned: "Ramesh Plumber",
    date: "2025-06-15",
    time: "10:30 AM",
  },
  {
    id: "REQ-002",
    title: "Fan Not Working",
    description: "Ceiling fan stopped working",
    category: "Electrical",
    resident: "Priya Mehta",
    image: profile2,
    flat: "B-203",
    priority: "Medium",
    status: "In Progress",
    assigned: "Suresh Electrician",
    date: "2025-06-18",
    time: "02:15 PM",
  },
  {
    id: "REQ-003",
    title: "Wall Crack",
    description: "Crack appeared in bedroom wall",
    category: "Civil",
    resident: "Amit Verma",
    image: profile3,
    flat: "C-305",
    priority: "High",
    status: "Completed",
    assigned: "Civil Team",
    date: "2025-06-10",
    time: "11:45 AM",
  },
  {
    id: "REQ-004",
    title: "Garden Cleaning",
    description: "Need cleaning near entrance garden",
    category: "Gardening",
    resident: "Neha Singh",
    image: profile4,
    flat: "D-102",
    priority: "Low",
    status: "Pending",
    assigned: "Garden Staff",
    date: "2025-06-20",
    time: "09:00 AM",
  },
  {
    id: "REQ-005",
    title: "Door Repair",
    description: "Main door hinge broken",
    category: "Carpentry",
    resident: "Suresh Patel",
    image: profile5,
    flat: "E-404",
    priority: "Medium",
    status: "Overdue",
    assigned: "Carpenter Team",
    date: "2025-06-05",
    time: "04:20 PM",
  },
   {
    id: "REQ-010",
    title: "Fan Not Working",
    description: "Ceiling fan stopped working",
    category: "Electrical",
    resident: "Priya Mehta",
    image: profile2,
    flat: "B-203",
    priority: "Medium",
    status: "In Progress",
    assigned: "Suresh Electrician",
    date: "2025-06-18",
    time: "02:15 AM",
  },
  {
    id: "REQ-011",
    title: "All Not Working",
    description: "Ceiling fan stopped working",
    category: "Electrical",
    resident: "Priya Mehta",
    image: profile2,
    flat: "B-203",
    priority: "Medium",
    status: "In Progress",
    assigned: "Suresh Electrician",
    date: "2025-06-18",
    time: "02:15 AM",
  },
];

